version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        mix_env: prod
        phoenix_secret: $PHOENIX_SECRET
        tls_key_path: $TLS_KEY_PATH
        tls_cert_path: $TLS_CERT_PATH
        fb_app_id: $FB_APP_ID
        fb_secret: $FB_SECRET
    environment:
      PORT: "4000"
      DB_HOST: "db"
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    ports:
      - "80:4000"
      - "443:443"
    restart: always
  assets:
    environment:
      NODE_ENV: production
  db:
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: always
