version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        mix_env: prod
    environment:
      PORT: "4000"
      DB_HOST: "db"
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      PHOENIX_SECRET: $PHOENIX_SECRET
      TLS_KEY_PATH: $TLS_KEY_PATH
      TLS_CERT_PATH: $TLS_CERT_PATH
    ports:
      - "80:4000"
      - "443:443"
    restart: always
  assets:
    environment:
      NODE_ENV: production
  db:
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: always
